### ISSUE TITLE
Screenshots are not uploaded to RP if the "it" part of the test contains comma or slash

### ISSUE THREAD

**Issue by tamasmagyar** [reportportal/agent-js-cypress#78] opened 2021-03-26 08:01 UTC
examples: 
`it('user logs in, and logs out', function () {
    // some action
}`

`it('something/another thing', function () {
    // some action
}`

**Comment by AmsterGet** [comment] 2024-07-26 16:02
Closed as a duplicate of https://github.com/reportportal/agent-js-cypress/issues/68

**Closed by AmsterGet** 2024-07-26 16:02 UTC
