### ISSUE TITLE
Using agent-js-cypres along with mochawesome reporter via cypress-multi-reporters

### ISSUE THREAD

**Issue by mleonard0826** [reportportal/agent-js-cypress#46] opened 2020-06-05 15:42 UTC
I'm trying to both generate a local report using mochawesome and send test data to ReportPortal.io for my Cypress project. I think the config should be something like:

```
    "reporter": "cypress-multi-reporters",
    "reporterOptions": {
        "reporterEnabled": "agent-js-cypress/rp-reporter.js, mochawesome",
        "agentJsCypressRpReporterReporterOptions": {
            "endpoint": "http://localhost:8080/api/v1",
            "token": "6df05ba5-98b5-4203-9106-a5867be16113",
            "launch": "Cypress Test Run",
            "project": "demoday",
            "description": "Test run from gde-cypress-poc",
            "isLaunchMergeRequired": true
        },
        "mochawesomeReporterOptions": {
            "reportDir": "cypress/reports/mocha",
            "quite": true,
            "overwrite": false,
            "html": false,
            "json": true
        }
    }
```

When I try that, I just ECONNREFUSED errors from reportportal. Is it possible to use the rp-reporter in tandem with another in this way? If not currently, is that planned for the future?

**Comment by paulmwhite** [comment] 2020-06-09 15:13
This works for me:

cypress.json
`  "reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "reporter.json"
  },`

reporter.json
`{
  "reporterEnabled": "mochawesome, agent-js-cypress",
  "mochawesomeReporterOptions": {
    "reportDir": "cypress/artifacts/reports/",
    "reportFilename": "value",
    "reportTitle": "value ",
    "overwrite": true,
    "html": false,
    "json": true
  },
  "agentJsCypressReporterOptions": {
    "endpoint": "value/api/v2",
    "token": "value",
    "launch": "value",
    "project": "value",
    "description": "value",
    "autoMerge": true
  }
}`

**Comment by diogogt** [comment] 2020-06-11 12:44
It's works for me, try to remove the **rp-reporter.js** and use just:
` "reporterEnabled": "agent-js-cypress, mochawesome",`

**Comment by mleonard0826** [comment] 2020-06-11 13:32
Thanks to you both. After following Paul's suggestion, I'm no longer getting errors in command line regarding the use of the reporters. My tests are still hanging with the launch never finishing, though (which was happening with just using agent-js-cypress too). I see other open issues that reference that problem. Has either of you gotten the launches to complete successfully without having to stop them manually?

**Comment by diogogt** [comment] 2020-06-11 14:29
On slack I found a suggest to use the dependencies from master:
`"agent-js-cypress": "https://github.com/reportportal/agent-js-cypress.git#master",`
In some cases some specs didn't finish and I put to finish automatically on ReportPortal

**Comment by vishallanke** [comment] 2020-06-16 16:54
I have observed that when I execute Git Pipeline, test cases does not get uploaded inside report portal. It happens only when few test gets failed from suite. If spec passes, then no issues, spec and tests gets uploaded. But if any test from spec test failed, then test cases does not get uploaded to report portal.

Any solution ... ?

**Comment by ElenaRomanchuk** [comment] 2020-06-29 20:35
There is an issues #37 and #35 regarding not-finished lanches.

@diogogt , we will appreciate if you can describe in details cases when launches stuck in relevant issue (or create separate issue if it's needed). This could help us to reproduce a bug. Thank you!

I close this issue because the original problem was resolved.

**Closed by ElenaRomanchuk** 2020-06-29 20:35 UTC
