### ISSUE TITLE
cy.setStatusPassed(suite) usage throws error, we need to see the steps in the report portal

### ISSUE THREAD

**Issue by srihariharanprabhakaran** [reportportal/agent-js-cypress#155] opened 2023-01-25 13:46 UTC
Configuration property not set! Neither for cypress <= 9 nor cypress >= 10
Error: Configuration property not set! Neither for cypress <= 9 nor cypress >= 10
    at getTotalSpecs (C:\Users\**\cypress-cucumber-reportportal\node_modules\@reportportal\agent-js-cypress\lib\utils.js:252:11)
    at CypressReporter.calcTotalLaunches (C:\Users\**\cypress-cucumber-reportportal\node_modules\@reportportal\agent-js-cypress\lib\cypressReporter.js:202:39)
    at R.<anonymous> (C:\Users\**cypress-cucumber-reportportal\node_modules\@reportportal\agent-js-cypress\lib\cypressReporter.js:155:23)
    at R.emit (node:events:539:35)
    at S.emit (<embedded>:4532:16654)
    at Object.onMocha (<embedded>:4579:425395)
    at p.<anonymous> (<embedded>:4579:66778)
    at p.emit (node:events:527:28)
    at p.emitUntyped (<embedded>:4290:84346)
    at <embedded>:4290:91863
    at process.processTicksAndRejections (node:internal/process/task_queues:78:11)

**Comment by AmsterGet** [comment] 2023-01-25 13:59
Hello @srihariharanprabhakaran !
Could you please provide your cypress config file and agent-js-cypress config as well?

**Comment by srihariharanprabhakaran** [comment] 2023-01-25 14:41
We don't have agent-js-cypress config file in the project, can you please share if we need to add so.

cypress.config.ts:

import { defineConfig } from "cypress";
import createBundler from "@bahmutov/cypress-esbuild-preprocessor";
import { addCucumberPreprocessorPlugin } from "@badeball/cypress-cucumber-preprocessor";
import createEsbuildPlugin from "@badeball/cypress-cucumber-preprocessor/esbuild";
import registerReportPortalPlugin from "@reportportal/agent-js-cypress/lib/plugin";

export default defineConfig({  
  reporter: '@reportportal/agent-js-cypress',
  reporterOptions: {
    endpoint: 'http://<url>/api/v1',
    token: 'token',
    launch: 'LAUNCH_DESCRIPTION_cypress_cucumber_test',
    project: 'default_personal',
    description: 'LAUNCH_DESCRIPTION_cypress_cucumber_test',
    reportHooks: false,
    autoMerge: true,
    mode: 'DEBUG',
    attributes: [
      {
        key: 'env',
        value: 'intest',
      },
    ],
    restClientConfig: {
      timeout: 300000,
    },
    "scenarioBasedStatistics":true,
  },
  e2e: {
    specPattern: "**/*.feature",
    async setupNodeEvents(
      on: Cypress.PluginEvents,
      config: Cypress.PluginConfigOptions
    ): Promise<Cypress.PluginConfigOptions> {
      // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
      await addCucumberPreprocessorPlugin(on, config);
      await registerReportPortalPlugin(on,config);
      on(
        "file:preprocessor",
        createBundler({
          plugins: [createEsbuildPlugin(config)],
        })
      );

      // Make sure to return the config object as it might have been modified by the plugin.
      return config;      
    },
  },
});

commands.js :
import '@reportportal/agent-js-cypress/lib/commands/reportPortalCommands';

plugin/indes.js:
const registerReportPortalPlugin = require('@reportportal/agent-js-cypress/lib/plugin');
module.exports = (on, config) => registerReportPortalPlugin(on, config);

**Comment by AmsterGet** [comment] 2023-01-25 15:01
No separate config file required for `agent-js-cypress` if you provided its options in the `cypress.config.ts`.

Note that the `plugin/index.js` file isn't required if you call `registerReportPortalPlugin` in `setupNodeEvents`.

Another note that this agent doesn't support `scenarioBasedStatistics` from `agent-js-cucumber` - there is a [feature request](https://github.com/reportportal/agent-js-cucumber/issues/96) on `cucumber-preprocessor` in its repository, but for now with no ETA. So the issue may be caused by the mix of cypress and cucumber.

**Comment by srihariharanprabhakaran** [comment] 2023-01-25 15:33
I have remove the lugin/index.js and also removed "scenarioBasedStatistics". But we still see the error  in using cy.setStatus(status, suite).  There is a note in "https://github.com/reportportal/agent-js-cypress#readme" we can use cy.setStatus(status, suite). can you provide some details on that usage?

**Comment by AmsterGet** [comment] 2023-01-25 16:13
So the reporter works fine if you don't use the `cy.setStatus(status, suite)`, am I right?
You can find the examples [here](https://github.com/reportportal/examples-js/blob/master/example-cypress/cypress/e2e/rp-features/statusesTest.cy.js).
Please note that these methods [should be called inside of corresponding test/suite](https://github.com/reportportal/agent-js-cypress#finish-launchtest-item-with-status).

These methods are optional. This way the RP will automatically set the statuses based on information from the test framework, but you can use these methods to override them.

**Comment by AmsterGet** [comment] 2023-03-06 15:00
Hello @srihariharanprabhakaran !
Is this issue still relevant or we can close it?
Thanks.

**Comment by AmsterGet** [comment] 2024-07-26 15:31
Hello @srihariharanprabhakaran !
I will close this issue due to inactivity.
Feel free to reopen it or create a new one if necessary.

**Closed by AmsterGet** 2024-07-26 15:31 UTC
