### ISSUE TITLE
Tests hanging in project with large number of files

### ISSUE THREAD

**Issue by Saoife** [reportportal/agent-js-cypress#73] opened 2021-03-09 17:14 UTC
Sometimes in a project with a large number of files, the test finishes before the agent can finish searching for any screenshots to attach. The tests in reportportal will hang after that until they time out.

**Comment by tamasmagyar-bridge** [comment] 2021-03-23 09:28
Duplicate? https://github.com/reportportal/agent-js-cypress/issues/64

**Comment by tamasmagyar** [comment] 2021-03-23 09:29
Duplicate? https://github.com/reportportal/agent-js-cypress/issues/64

**Comment by ElasticDragonfly** [comment] 2021-04-01 09:40
> Duplicate? #64

I think that's a different issue, for this one it's the individual tests that don't get completed. Auto-merge doesn't seem to change anything either

**Comment by tamasmagyar** [comment] 2021-04-01 09:47
> > Duplicate? #64
> 
> I think that's a different issue, for this one it's the individual tests that don't get completed. Auto-merge doesn't seem to change anything either

I think it's kind of a similar issue. The problem is Report Portal closes the "connection" and doesn't wait until the screenshots are uploaded in your case. On #64 it doesn't wait for the auto-merge. Can you check the workaround mentioned in #64 ?

**Comment by AmsterGet** [comment] 2022-01-27 13:19
Hello @ElasticDragonfly !
Can it be connected with https://github.com/reportportal/agent-js-cypress/issues/76?
This issue already fixed in v5.0.3.

**Comment by AmsterGet** [comment] 2024-07-26 16:10
Hello @Saoife !
The screenshot mechanism has been completely rewritten and released in version [5.1.2](https://github.com/reportportal/agent-js-cypress/releases/tag/v5.1.2).
Have you tried using it?
Please check your issue with the latest agent version.
Looking forward to your feedback!

**Comment by AmsterGet** [comment] 2024-08-08 15:08
I'll close this issue.
Feel free to reopen it if your request is still relevant.

**Closed by AmsterGet** 2024-08-08 15:08 UTC
Labels: bug
